name: Build and Test Local

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup-container:
    uses: ./.github/workflows/container_setup.yaml
    with:
      container_type: ubuntu-cuda

  build_and_test:
    needs: setup-container
    runs-on: local-gpu-numa-runnerg
    container:
      image: ${{ needs.setup-container.outputs.container_image }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build C++
        run: |
          git config --global --add safe.directory '*'
          eval "$(conda shell.bash hook)"
          conda activate quake-env
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release \
                -DQUAKE_USE_NUMA=ON \
                -DQUAKE_ENABLE_GPU=ON \
          		-DCMAKE_CUDA_COMPILER=/usr/local/cuda/bin/nvcc \
                -DCMAKE_CUDA_ARCHITECTURES="75" \
                -DTORCH_CUDA_ARCH_LIST="7.5" \
                -DBUILD_TESTS=ON \
                -DQUAKE_USE_AVX512=ON \
                ../
          make bindings -j
          make quake_tests -j

      - name: Run C++ Tests
        shell: bash
        run: |
          OMP_NUM_THREADS=1 ./build/test/cpp/quake_tests

      - name: Run Python Tests
        shell: bash
        run: |
          git config --global --add safe.directory '*'
          eval "$(conda shell.bash hook)"
          conda activate quake-env
          pip install --no-use-pep517 .
          pip install pytest
          python -m pytest test/python